name: Manual build and deploy

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sustainable-materials-app    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'                  # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                         # set this to the .NET version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Install Azure CLI
      run: |
        Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
        rm .\AzureCLI.msi

    - name: Generate deployment script
      run: |
        echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" > publish_profile.xml
        az login --service-principal -u "http://${{ env.AZURE_WEBAPP_NAME }}" -p "${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
        az webapp deployment source config-zip --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" --name "${{ env.AZURE_WEBAPP_NAME }}" --src "${{env.DOTNET_ROOT}}/myapp"

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" --name "${{ env.AZURE_WEBAPP_NAME }}" --src "${{env.DOTNET_ROOT}}/myapp"
